name: Theme Check

on: [push]

permissions:
  contents: read
  checks: write

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.' # Change to './dist' if your theme is built there
          base: main       # Optional, only needed for PR comparisons
